project_name: restreamer
before:
  hooks:
    - go mod tidy
builds:
- dir: cmd/restreamer
  goos:
    - linux
    - windows
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
    - mips
    - mipsle
  ignore:
    - goos: windows
      goarch: arm
  ldflags:
  - -s -w -X main.version={{.Version}} 
archives:
  - replacements:
      darwin: macos
checksum:
  name_template: 'checksums.txt'